use job_bop_new
go
insert into Mas_Branch select * from job_bop.dbo.Mas_Branch
go
insert into Mas_CurrencyCode select * from job_bop.dbo.Mas_CurrencyCode
go
insert into Mas_User select * from job_bop.dbo.Mas_User
go
insert into Mas_UserAuth select * from job_demo.dbo.Mas_UserAuth where UserID='Admin'
go
insert into Mas_Company select * from job_bop.dbo.Mas_Company
go
insert into Mas_Vender 
select 
VenCode,
BranchCode,
TaxNumber,
Title,
TName,
English,
TAddress1,
TAddress2,
EAddress1,
EAddress2,
Phone,
FaxNumber,
LoginName,
LoginPassword,
GLAccountCode,
ContactAcc,
ContactSale,
ContactSupport1,
ContactSupport2,
ContactSupport3,
WEB_SITE
from job_bop.dbo.Mas_Vender
go
insert into Job_Order select * from job_bop.dbo.Job_Order
go
insert into Job_ClearDetail select * from Job_bop.dbo.Job_ClearDetail 
go
insert into Job_ClearHeader select * from Job_Bop.dbo.Job_ClearHeader 
go
INSERT INTO Job_InvoiceHeader (
BranchCode,
DocNo,
DocDate,
CustCode,
CustBranch,
BillToCustCode,
BillToCustBranch,
ContactName,
EmpCode,
PrintedBy,
PrintedDate,
PrintedTime,
RefNo,
VATRate,
TotalAdvance,
TotalCharge,
TotalIsTaxCharge,
TotalIs50Tavi,
TotalVAT,
Total50Tavi,
TotalCustAdv,
TotalNet,
BillAcceptDate,
BillIssueDate,
BillAcceptNo,
Remark1,
Remark2,
Remark3,
Remark4,
Remark5,
Remark6,
Remark7,
Remark8,
Remark9,
Remark10,
CancelReson,
CancelProve,
CancelDate,
CancelTime,
ShippingRemark,
CurrencyCode,
ExchangeRate,
ForeignNet,
SumDiscount,
DiscountRate,
DiscountCal,
TotalDiscount,
DueDate,
CreateDate
)
SELECT
i.BranchCode,
i.DocNo,
i.DocDate,
i.CustCode,
i.CustBranch,
i.BillToCustCode,
i.BillToCustBranch,
i.ContactName,
i.EmpCode,
i.PrintedBy,
i.PrintedDate,
i.PrintedTime,
i.RefNo,
i.VATRate,
i.TotalAdvance,
i.TotalCharge,
i.TotalIsTaxCharge,
i.TotalIs50Tavi1+i.TotalIs50Tavi2,
i.TotalVAT,
i.Total50Tavi1+i.Total50Tavi2,
i.TotalCustAdv,
i.TotalNet,
i.BillDate,
b.DocDate,
i.BillAcceptNo,
i.Remark1,
i.Remark2,
i.Remark3,
i.Remark4,
i.Remark5,
i.Remark6,
i.Remark7,
i.Remark8,
i.Remark9,
i.Remark10,
i.CancelReson,
i.CancelProve,
i.CancelDate,
i.CancelTime,
i.ShippingRemark,
i.CurrencyCode,
i.ExchangeRate,
i.ForeignAmt,
0,
0,
0,
0,
NULL,
i.DocDate
FROM Job_bop.dbo.Job_BillingHeader i
left join Job_Bop.dbo.Job_BillAnn b
on i.BillAcceptNo=b.DocNO
go

INSERT INTO Job_InvoiceDetail (
BranchCode,
DocNo,
ItemNo,
SICode,
SDescription,
ExpSlipNO,
SRemark,
CurrencyCode,
ExchangeRate,
Qty,
QtyUnit,
UnitPrice,
FUnitPrice,
Amt,
FAmt,
DiscountType,
DiscountPerc,
AmtDiscount,
FAmtDiscount,
Is50Tavi,
Rate50Tavi,
Amt50Tavi,
IsTaxCharge,
AmtVat,
TotalAmt,
FTotalAmt,
AmtAdvance,
AmtCharge,
CurrencyCodeCredit,
ExchangeRateCredit,
AmtCredit,
FAmtCredit,
VATRate
)
SELECT 
i.BranchCode,
i.DocNo,
i.ItemNo,
i.SICode,
i.SDescription,
i.ExpSlipNO,
i.SRemark,
i.CurrencyCode,
i.ExchangeRate,
1,
i.QtyUnit,
i.ForeignAmt*i.ExchangeRate,
i.ForeignAmt,
i.ForeignAmt*i.ExchangeRate,
i.ForeignAmt,
0,
isnull(i.DiscountPerc,0),
isnull(i.AmtDiscount,0),
isnull(i.ForeignDisc,0),
i.Is50Tavi,
i.Rate50Tavi,
(i.ForeignAmt*i.ExchangeRate)*i.Rate50Tavi*0.01,
i.IsTaxCharge,
(i.ForeignAmt*i.ExchangeRate)*0.07,
i.ForeignAmt*i.ExchangeRate,
i.ForeignAmt,
i.AmtAdvance,
i.AmtCharge,
'',
1,
0,
0,
7
FROM job_bop.dbo.Job_BillingDetail i
GO
INSERT INTO Job_SrvSingle (
SICode,
NameThai,
NameEng,
StdPrice,
UnitCharge,
CurrencyCode,
DefaultVender,
ProcessDesc,
GLAccountCodeSales,
GLAccountCodeCost,
IsTaxCharge,
Is50Tavi,
Rate50Tavi,
IsCredit,
IsExpense,
IsShowPrice,
IsHaveSlip,
IsPay50TaviTo,
IsLtdAdv50Tavi,
IsUsedCoSlip,
GroupCode)
SELECT
s.SICode,
s.NameThai,
s.NameEng,
s.StdPrice,
s.UnitCharge,
s.CurrencyCode,
s.DefaultVender,
s.ProcessDesc,
s.GLAccountCode,
s.GLAccountCode,
s.IsTaxCharge,
s.Is50Tavi,
s.Rate50Tavi,
s.IsCredit,
s.IsExpense,
s.IsShowPrice,
s.IsHaveSlip,
s.IsPay50TaviTo,
s.IsLtdAdv50Tavi,
s.IsUsedCoSlip,
'LTD'
FROM job_Bop.dbo.Job_SrvSingle s
GO
INSERT INTO Job_SrvGroup SELECT 'LTD',
'Default Expenses',
'',
0,
0,
0,
0,
0,
0,
0,
0 
GO
INSERT INTO Job_BillAcceptHeader (
BranchCode,
BillAcceptNo,
BillDate,
CustCode,
CustBranch,
BillRecvBy,
BillRecvDate,
DuePaymentDate,
BillRemark,
CancelReson,
CancelProve,
CancelDate,
CancelTime,
EmpCode,
RecDateTime,
TotalCustAdv,
TotalAdvance,
TotalChargeVAT,
TotalChargeNonVAT,
TotalVAT,
TotalWH,
TotalDiscount,
TotalNet)
SELECT
BranchCode,
DocNO,
DocDate,
CustCode,
CustBranch,
RecvBy,
RecvDate,
PaymentDate,
TRemark,
CancelReson,
CancelProve,
CancelDate,
CancelTime,
'ADMIN',
GetDate(),
0,
0,
0,
0,
0,
0,
0,
0 
FROM job_bop.dbo.Job_BillAnn
go
INSERT INTO Job_BillAcceptDetail (
BranchCode,
BillAcceptNo,
ItemNo,
InvNo,
AmtAdvance,
AmtChargeNonVAT,
AmtChargeVAT,
AmtWH,
AmtVAT,
AmtTotal,
CurrencyCode,
ExchangeRate,
AmtCustAdvance,
AmtForeign,
InvDate,
RefNo,
AmtVATRate,
AmtWHRate,
AmtDiscount,
AmtDiscRate)
SELECT 
b.BranchCode,
b.DocNO,
b.ItemNo,
b.BillNo,
b.AmtAdvance,
b.AmtChargeNoVAT,
b.AmtChargeVAT,
b.AmtWH1+b.AmtWH3,
b.AmtVAT,
b.AmtTotal,
b.CurrencyCode,
b.ExchangeRate,
i.TotalCustAdv,
b.ForeignAmt,
i.DocDate,
i.RefNo,
i.VATRate,
0,
0,
0 FROM
job_bop.dbo.Job_BillAnnSub b inner join job_bop.dbo.Job_BillingHeader I 
ON b.BillNo=i.DocNo
GO
UPDATE h
SET h.TotalCustAdv=d.TotalCustAdv,
h.TotalAdvance=d.TotalAdvance,
h.TotalChargeVAT=d.TotalChargeVAT,
h.TotalChargeNonVAT=d.TotalChargeNoVAT,
h.TotalVAT=d.TotalVAT,
h.TotalWH=d.TotalWH,
h.TotalDiscount=0,
h.TotalNet=d.TotalNet 
FROM Job_BillAcceptHeader h
inner join (
	select BranchCode,BillAcceptNo ,
	sum(AmtCustAdvance) as TotalCustAdv,
	sum(AmtAdvance) as TotalAdvance,
	sum(AmtChargeVAT) as TotalChargeVAT,
	sum(AmtChargeNonVAT) as TotalChargeNoVAT,
	sum(AmtVAT) as TotalVAT,
	sum(AmtWH) as TotalWH,
	sum(AmtTotal) as TotalNet
	from Job_BillAcceptDetail
	group by BranchCode,BillAcceptNo 
) d
on h.BranchCode=d.BranchCode and h.BillAcceptNo=d.BillAcceptNo
GO
INSERT INTO Job_ReceiptHeader (
BranchCode,
ReceiptNo,
ReceiptDate,
ReceiptType,
CustCode,
CustBranch,
BillToCustCode,
BillToCustBranch,
TotalCharge,
TotalVAT,
Total50Tavi,
TotalNet,
TRemark,
EmpCode,
PrintedBy,
PrintedDate,
PrintedTime,
ReceiveBy,
ReceiveDate,
ReceiveTime,
ReceiveRef,
CancelReson,
CancelProve,
CancelDate,
CancelTime,
CurrencyCode,
ExchangeRate,
FTotalNet)
SELECT
BranchCode,
InvNo,
InvDate,
'TAX',
CustCode,
CustBranch,
BillToCustCode,
BillToCustBranch,
TotalCharge,
TotalVAT,
Total50Tavi,
TotalNet,
TRemark,
EmpCode,
PrintedBy,
PrintedDate,
PrintedTime,
ReceiveBy,
ReceiveDate,
ReceiveTime,
ReceiveRef,
CancelReson,
CancelProve,
CancelDate,
CancelTime,
CurrencyCode,
ExchangeRate,
ForeignAmt 
FROM Job_bop.dbo.Job_TaxInvoice
GO
INSERT INTO Job_ReceiptDetail (
BranchCode,
ReceiptNo,
ItemNo,
CreditAmount,
CashAmount,
TransferAmount,
ChequeAmount,
ControlNo,
VoucherNo,
ControlItemNo,
InvoiceNo,
InvoiceItemNo,
SICode,
SDescription,
VATRate,
Rate50Tavi,
Amt,
AmtVAT,
Amt50Tavi,
Net,
DCurrencyCode,
DExchangeRate,
FAmt,
FAmtVAT,
FAmt50Tavi,
FNet)
SELECT 
r.BranchCode,
r.InvNo,
ROW_NUMBER() OVER(PARTITION BY r.BranchCode,r.InvNo ORDER BY r.BranchCode,r.InvNo),
0,
0,
((d.AmtCharge+d.AmtAdvance)*d.ExchangeRate)*(1+((h.VatRate-d.Rate50Tavi)*0.01)),
0,
'',
'',
0,
h.DocNo,
d.ItemNo,
r.SICode,
r.SDescription,
h.VATRate,
r.Rate50Tavi,
r.AmtCharge,
r.AmtVAT,
r.Amt50Tavi,
r.AmtCharge+r.AmtVAT-r.Amt50Tavi,
d.CurrencyCode,
d.ExchangeRate,
(d.AmtCharge+d.AmtAdvance),
((d.AmtCharge+d.AmtAdvance))*(((h.VatRate)*0.01)),
((d.AmtCharge+d.AmtAdvance))*(((d.Rate50Tavi)*0.01)),
((d.AmtCharge+d.AmtAdvance))*(1+((h.VatRate-d.Rate50Tavi)*0.01))
FROM Job_bop.dbo.Job_BillingDetail d INNER JOIN job_bop.dbo.Job_BillingHeader h
ON d.DocNo=h.DocNo 
INNER JOIN job_bop.dbo.Job_TaxInvoiceDetail r ON
h.TaxInvNo=r.InvNo 
and d.SICode=r.SICode
GO
